services:
  # Service Database
  db:
    image: postgres:15-alpine
    container_name: rakit-tiket-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    # TAMBAHAN 1: Healthcheck untuk memastikan Postgres benar-benar siap
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service Aplikasi Go Kamu
  app:
    build: .
    container_name: rakit-tiket-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    # TAMBAHAN 2: Ubah depends_on menjadi format panjang (condition)
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_DATABASE}
      PORT: ${PORT}
      MIGRATION_PATH: /app/internal/pkg/scripts
      LOG_ENVIRONMENT: production
      APP_FILE_PATH: ${APP_FILE_PATH}
      FILE_PATH: ${FILE_PATH}

  frontend:
    build:
      context: ../rakit-tiket-fe
      dockerfile: Dockerfile
    container_name: rakit-tiket-fe
    ports:
      - "3000:80"
    restart: always
    environment:
      - VITE_API_BASE_URL=http://212.85.24.75:8000/api

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: rakit-tiket-swagger
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /docs/rakit-tiket.open-api.yaml
    volumes:
      - ./docs:/docs

volumes:
  pgdata: